name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Inject credentials
        run: |
          echo "gradle.publish.key=${{ secrets.PUBLISH_API }}" >> ~/.gradle/gradle.properties
          echo "gradle.publish.secret=${{ secrets.PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties

      - name: Publish
        run: ./gradlew publishPlugins
